from ai.state import AgentState
from ai.router import llm, llm_with_structure, question_router
from langchain_classic.document_loaders import PyPDFLoader
from langchain_classic.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_classic.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph,START,END
from langgraph.graph.message import add_messages
from langchain_astradb import AstraDBVectorStore
from langchain.messages import AIMessage,HumanMessage
from pydantic import BaseModel, Field, field_validator
from typing import List,Literal,Optional
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.checkpoint.memory import InMemorySaver
from langchain_classic.indexes.vectorstore import VectorStoreIndexWrapper
from ai.tools.resume import tools
from langchain_anthropic import ChatAnthropic
from dotenv import load_dotenv
import os
load_dotenv()
anthropic_api_key=os.environ['ANTHROPIC_API_KEY']

chat_history=[]

memory = InMemorySaver()


class Answer(BaseModel):
    name: Optional[str] = Field(None, description="Full name of the applicant")
    skills: Optional[List[str]] = Field(default_factory=list, description="Technical and soft skills of the applicant")
    education: Optional[str] = Field(None, description="Education background of the applicant")
    work_experience: Optional[List[str]] = Field(default_factory=list, description="Work experience of the applicant")
    certifications: Optional[List[str]] = Field(default_factory=list, description="List of certifications the applicant has")
    achievements: Optional[List[str]] = Field(default_factory=list, description="List of achievements of the applicant")

Answer.model_rebuild()

class LLMResponseStructure(BaseModel):
    generation: Optional[str] = Field(None, description="Answer generated by the llm")
    applicant: Optional[Answer] = Field(None, description="The data of the applicant")
    confidence: Optional[float] = Field(None, description="0.0 = low confidence, 1.0 = high confidence")
    source: Optional[Literal['resume', 'inference']] = Field(None, description="source of the answer")
    missing_data: Optional[List[str]] = Field(default_factory=list, description="MUST be a JSON array. Use [] if nothing is missing. Never use a plain string.")

    @field_validator('missing_data', mode='before')
    @classmethod
    def coerce_missing_data(cls, v):
        if v is None or v == "":
            return []
        if isinstance(v, str):
            return [v]
        return v

LLMResponseStructure.model_rebuild()


def get_vectorstore():
    embeddings=HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    astra_vector_store = AstraDBVectorStore(
    collection_name="langchain_integration_demo",
    embedding=embeddings,
    token=os.environ['ASTRA_DB_APPLICATION_TOKEN'],
    api_endpoint=os.environ['ASTRA_DB_API_ENDPOINT'],
    namespace=os.environ['ASTRA_DB_KEYSPACE'],
    )
    return astra_vector_store

astra_vector_store =get_vectorstore()

def input_validation(state:AgentState):
    """Check if the input given is valid"""


def route_question(state:AgentState):
    """Route question to wiki extract_resume_data or chat 
    Args:
    state(dict): The current graph state
    Returns:
    str=Next node to call
    
    """
    question=state['messages'][-1].content

    next_node:str=question_router.invoke({"question":question})
    print('route',next_node)
    print('que',question)
    if next_node is not None and next_node.datasource is None:
            return route_question(state) 
    return next_node.datasource
    

    

def extract_resume_data(state:AgentState):
    print('extract_resume_data')
    """Extract the data from the resume
    Args:
    state(dict):The current graph state
    Returns:
    State(dict): New key added to state
    """
    file_path=state['file_path']
    loader=PyPDFLoader(file_path=file_path)
    text_splitter=RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=200)
    docs=loader.load_and_split(text_splitter=text_splitter)
    
    user_id=state['user_id']
    for doc in docs:
        doc.metadata["user_id"] = user_id

    user_id=state['user_id']
    print('user_id',user_id)
    astra_vector_store.add_documents(docs)


    llm=ChatAnthropic(model="claude-sonnet-4-6", anthropic_api_key=anthropic_api_key)
    llm=llm.bind_tools(tools)

    retriever = astra_vector_store.as_retriever(
        search_type="similarity",
        search_kwargs={
            "filter": {"user_id": user_id}  # only this user's docs
        }
    )

    return {
        "messages":llm.invoke(state['messages']),
        "documents": [doc.page_content for doc in docs],
        "retriever": retriever
    }
    

def chat(state:AgentState):
    print('chat node')
    """
    Get answers to the question regarding the applicant
    Args:
    state(dict): The current graph state

    Returns:
    State(dict): New key added to state
    """
    question = ""
    last_msg = state['messages'][-1]

    # If last message is from AI (response to tool), get the user question before it
    if isinstance(last_msg, AIMessage):
        raw = state['messages'][-2].content
    else:
        raw = last_msg.content

    if isinstance(raw, list):
        question = " ".join(
            block.get("text", "") for block in raw if isinstance(block, dict)
        )
    else:
        question = raw
    
    
    

    SYSTEM_PROMPT = """You are an advanced resume analysis assistant.

Your task is to answer questions about a candidate by returning ONLY a valid JSON object.

Return this exact JSON structure (no other text):
{{
  "generation": "your detailed answer here",
  "applicant": {{
    "name": "full name or null",
    "skills": ["skill1", "skill2"] or [],
    "education": "education or null",
    "work_experience": ["experience1", "experience2"] or [],
    "certifications": ["cert1"] or [],
    "achievements": ["achievement1"] or []
  }},
  "confidence": 0.0-1.0,
  "source": "resume" or "inference",
  "missing_data": []
}}

Instructions:
- Answer ONLY using information from the resume context.
- If information is not in resume, use "inference" as source and infer logically.
- Do NOT invent facts - if unknown, use null or empty arrays.
- generation should be a concise paragraph summarizing the analysis.

Resume Context:
{context}

==============================
Chat History:
{chat_history}
=============================="""

    prompt=ChatPromptTemplate.from_messages([("system",SYSTEM_PROMPT),("human","{input}")])

    user_id=state['user_id']
    print('user-id',user_id)

    retriever = astra_vector_store.as_retriever(
        search_type="similarity",
        search_kwargs={
            "filter": {"user_id": user_id}  # only this user's docs
        }
    )

    docs = retriever.invoke(question)
    context_str = "\n".join(doc.page_content for doc in docs) if docs else ""
    print(f'docs count: {len(docs) if docs else 0}')
    print(f'context_str length: {len(context_str)}')
    print(f'question: {question[:100] if question else "EMPTY"}')

    # Use ChatAnthropic with structured output for JSON responses
    chat_llm = ChatAnthropic(model="claude-sonnet-4-6", anthropic_api_key=anthropic_api_key)
    chat_llm_with_response = chat_llm.with_structured_output(LLMResponseStructure)

    rag_chain = (
        {
            "context": RunnableLambda(lambda x: context_str),
            "input": RunnableLambda(lambda x: question),
            "chat_history": RunnableLambda(lambda x: chat_history)
        }
        | prompt
        | chat_llm_with_response
    )

    res=rag_chain.invoke({"input": question, "chat_history": chat_history})
    print('rag_chain result type:', type(res))
    

    return {
        "answer":res,
    }

def checkResponse(state:AgentState):
    print('response')
    """
    Check the response given by the llm
    """
    answer=state['answer']

    print(answer.generation)
    print(answer.generation=='None')

    

    if answer.generation:
        return 'end'
    else:
        return 'chat'


def build_graph():
    workflow=StateGraph(AgentState)
    tool_node=ToolNode(tools=tools)
    workflow.add_node('extract_resume_data',extract_resume_data)
    workflow.add_node('chat',chat)
    workflow.add_node('tools',tool_node)
    workflow.add_node('checkResponse',checkResponse)

    workflow.add_conditional_edges(
        START,
        route_question,
        {
            'extract_resume_data':'extract_resume_data',
            'chat':'chat'
        }
    )

    workflow.add_conditional_edges(
        'extract_resume_data',
        tools_condition
    )
    workflow.add_edge('tools', 'extract_resume_data')
    workflow.add_edge('extract_resume_data', 'chat')
    workflow.add_conditional_edges(
        'chat',
        checkResponse,
        {
            'chat':'chat',
            'end':END
        }
    )

    graph=workflow.compile(checkpointer=memory)

    return graph

graph=build_graph()

